version: '3.4'
services:

  app:
    image: bmeme/mn-dev:2.2.1-jdk-11-openj9
    entrypoint: /bin/sleep infinity
    working_dir: /usr/src/app/
    volumes:
      - "../:/usr/src/app"
    environment:
      - MAVEN_CONFIG=/usr/src/app/.cache/.m2
      - TERM=xterm-256color
